def get_aemRaw_query(start_month, end_month, start_day, end_day):
    s = f"""
        SELECT 
        -- ,[SessionVisitorId]
        -- ,[VisitStartDateTime]
        -- ,[VisitPageNumber]
        -- ,[VisitNumber]
        -- ,[NewVisit]
        -- ,[EventList]
        --   ,[ExcludeHit]
        --   ,[HitSource]
        [DateTime_UTC]
        ,[PageURL]
        --   ,[PageName]
        ,[VisitReferrer]
        --    ,[VisitReferrerType]
        ,[VisitorDomain]
        --   ,[IPaddress]
        --   ,[Language]
        --   ,[PageType]
        --   ,[ContentType]
        --   ,[UTM_Source]
        --   ,[UTM_Medium]
        --   ,[UTM_Campaign]
        --   ,[UTM_Content]
        --   ,[UTM_Term]
        --   ,[VideoName]
        --   ,[FileDownload]
        --   ,[FileType]
        --   ,[FileCategory]
        --   ,[GatedContentURL]
        --   ,[GatedContentFormType]
        --   ,[GatedContentFormName]
        --   ,[External_Id]
        --   ,[External_Company]
        --   ,[External_Audience]
        --   ,[External_AudienceSegment]
        --   ,[External_Address]
        --   ,[External_City]
        --   ,[External_StateProv]
        --   ,[External_PostalCode]
        --   ,[External_Country]
        --   ,[External_Industry]
        --   ,[External_SubIndustry]
        --   ,[External_SIC]
        --   ,[External_Website]
        --   ,[External_BusPhone]
        --   ,[External_NAICS]
        --   ,[EloquaContactId]
        --   ,[EloquaGUID]
        ,[mcvisid]
        -- ,[GeoCity]
        ,[GeoCountry]
        --   ,[GeoDMA]
        --   ,[GeoRegion]
        --   ,[GeoPostalCode]
        --   ,[Post_PostalCode]
        --   ,[Post_PageName]
        --   ,[Post_PageURL]
        --   ,[UploadedAt]
        --   ,[PDFurl]
        --   ,[PDFtitle]
        --   ,[PDFpagecount]
        --   ,[BingeId]
        --   ,[BingeName]
        --   ,[BingeCriticalScore]
        --   ,[BingeCampaignId]
        --   ,[BingeScoredAsset]
        ,[BingeScoredAssetPath]
        -- ,[BingeScoredAssetScore]
        FROM [Staging].[aem].[RawTraffic]
        WHERE (VisitStartDateTime >= '2022-{start_month}-{start_day}') AND (VisitStartDateTime < '2022-{end_month}-{end_day}')
        """
    return s



def get_mcvisid_bridge_query():
    s = f"""
        WITH TMP1 AS (
        SELECT DISTINCT [EloquaContactId], [mcvisid]
        FROM [Staging].[aem].[RawTraffic]
        WHERE EloquaContactId <> '' AND VisitStartDateTime > '2022-04-01'
        ), 

        TMP2 AS (
        SELECT DISTINCT  TMP1.[mcvisid], elq.EloquaContactId, LOWER(elq.[EmailAddress]) AS "EmailAddress"
        FROM [Staging].[elq].[Contact] AS elq
        INNER JOIN TMP1 ON TMP1.EloquaContactId = elq.EloquaContactId
        WHERE elq.EloquaContactId <> ''
        )

        SELECT *
        FROM TMP2 
        """
    return s



def get_crm_lead_query():
    s = f"""
        SELECT [accountid]
            ,[accountidname]
            ,[address1_addressid]
            ,[address1_addresstypecode]
            ,[address1_addresstypecodename]
            ,[address1_city]
            ,[address1_country]
            ,[address1_county]
            ,[address1_fax]
            ,[address1_latitude]
            ,[address1_line1]
            ,[address1_line2]
            ,[address1_line3]
            ,[address1_longitude]
            ,[address1_name]
            ,[address1_postalcode]
            ,[address1_postofficebox]
            ,[address1_shippingmethodcode]
            ,[address1_shippingmethodcodename]
            ,[address1_stateorprovince]
            ,[address1_telephone1]
            ,[address1_telephone2]
            ,[address1_telephone3]
            ,[address1_upszone]
            ,[address1_utcoffset]
            ,[address2_addressid]
            ,[address2_addresstypecode]
            ,[address2_addresstypecodename]
            ,[address2_city]
            ,[address2_country]
            ,[address2_county]
            ,[address2_fax]
            ,[address2_latitude]
            ,[address2_line1]
            ,[address2_line2]
            ,[address2_line3]
            ,[address2_longitude]
            ,[address2_name]
            ,[address2_postalcode]
            ,[address2_postofficebox]
            ,[address2_shippingmethodcode]
            ,[address2_shippingmethodcodename]
            ,[address2_stateorprovince]
            ,[address2_telephone1]
            ,[address2_telephone2]
            ,[address2_telephone3]
            ,[address2_upszone]
            ,[address2_utcoffset]
            ,[budgetamount]
            ,[budgetamount_base]
            ,[budgetstatus]
            ,[budgetstatusname]
            ,[campaignid]
            ,[campaignidname]
            ,[companyname]
            ,[confirminterest]
            ,[confirminterestname]
            ,[contactid]
            ,[contactidname]
            ,[createdby]
            ,[createdbyname]
            ,[createdon]
            ,[createdonbehalfby]
            ,[createdonbehalfbyname]
            ,[customerid]
            ,[customeridname]
            ,[customeridtype]
            ,[decisionmaker]
            ,[decisionmakername]
            ,[donotbulkemail]
            ,[donotbulkemailname]
            ,[donotemail]
            ,[donotemailname]
            ,[donotfax]
            ,[donotfaxname]
            ,[donotphone]
            ,[donotphonename]
            ,[donotpostalmail]
            ,[donotpostalmailname]
            ,[donotsendmarketingmaterialname]
            ,[donotsendmm]
            ,[emailaddress1]
            ,[emailaddress2]
            ,[emailaddress3]
            ,[estimatedamount]
            ,[estimatedamount_base]
            ,[estimatedclosedate]
            ,[estimatedvalue]
            ,[evaluatefit]
            ,[evaluatefitname]
            ,[exchangerate]
            ,[fax]
            ,[firstname]
            ,[followemail]
            ,[followemailname]
            ,[fullname]
            ,[importsequencenumber]
            ,[industrycode]
            ,[industrycodename]
            ,[initialcommunication]
            ,[initialcommunicationname]
            ,[isautocreatename]
            ,[isprivatename]
            ,[jobtitle]
            ,[lastname]
            ,[lastonholdtime]
            ,[lastusedincampaign]
            ,[leadid]
            ,[leadqualitycode]
            ,[leadqualitycodename]
            ,[leadsourcecode]
            ,[leadsourcecodename]
            ,[masterid]
            ,[masterleadidname]
            ,[merged]
            ,[mergedname]
            ,[middlename]
            ,[mobilephone]
            ,[modifiedby]
            ,[modifiedbyname]
            ,[modifiedon]
            ,[modifiedonbehalfby]
            ,[modifiedonbehalfbyname]
            ,[msdyn_gdproptout]
            ,[msdyn_gdproptoutname]
            ,[msdyn_leadgrade]
            ,[msdyn_leadgradename]
            ,[msdyn_leadkpiid]
            ,[msdyn_leadkpiidname]
            ,[msdyn_leadscore]
            ,[msdyn_leadscoretrend]
            ,[msdyn_leadscoretrendname]
            ,[msdyn_predictivescoreid]
            ,[msdyn_predictivescoreidname]
            ,[msdyn_salesassignmentresult]
            ,[msdyn_salesassignmentresultname]
            ,[msdyn_segmentid]
            ,[msdyn_segmentidname]
            ,[need]
            ,[needname]
            ,[numberofemployees]
            ,[onholdtime]
            ,[originatingcaseid]
            ,[originatingcaseidname]
            ,[overriddencreatedon]
            ,[ownerid]
            ,[owneridname]
            ,[owneridtype]
            ,[owningbusinessunit]
            ,[owningteam]
            ,[owninguser]
            ,[pager]
            ,[parentaccountid]
            ,[parentaccountidname]
            ,[parentcontactid]
            ,[parentcontactidname]
            ,[participatesinworkflow]
            ,[participatesinworkflowname]
            ,[preferredcontactmethodcode]
            ,[preferredcontactmethodcodename]
            ,[prioritycode]
            ,[prioritycodename]
            ,[processid]
            ,[purchaseprocess]
            ,[purchaseprocessname]
            ,[purchasetimeframe]
            ,[purchasetimeframename]
            ,[qualifyingopportunityid]
            ,[qualifyingopportunityidname]
            ,[ra_account]
            ,[ra_accountname]
            ,[ra_areyouengagedwithraoradistributor]
            ,[ra_areyouengagedwithraoradistributorname]
            ,[ra_blockreroutetodistributor]
            ,[ra_blockreroutetodistributorname]
            ,[ra_businessprocess]
            ,[ra_businessprocessname]
            ,[ra_channeltomarket]
            ,[ra_channeltomarketname]
            ,[ra_cnvcmpmostrecent]
            ,[ra_cnvcmporiginal]
            ,[ra_cnvdatemostrecentcmp]
            ,[ra_cnvdatemostrecentsrc]
            ,[ra_cnvdateoriginal]
            ,[ra_cnvsrccmpidmostrecent]
            ,[ra_cnvsrccmpidoriginal]
            ,[ra_cnvsrcmostrecent]
            ,[ra_cnvsrcoriginal]
            ,[ra_contact]
            ,[ra_contactname]
            ,[ra_datasrccode]
            ,[ra_datemodified]
            ,[ra_datesalesaccepted]
            ,[ra_datesalesqualified]
            ,[ra_dateteleaccepted]
            ,[ra_dateteleassigned]
            ,[ra_datetelequalified]
            ,[ra_demandsource]
            ,[ra_demandsourcename]
            ,[ra_emailwhoknowswhom]
            ,[ra_funding]
            ,[ra_fundingname]
            ,[ra_generalengagementscore]
            ,[ra_isthereanactiveneed]
            ,[ra_isthereanactiveneedname]
            ,[ra_ketplaysection]
            ,[ra_ketplaysectionname]
            ,[ra_keyplayurl]
            ,[ra_leadacceptanceduedate]
            ,[ra_leadlineitemcount]
            ,[ra_leadqualificationduedate]
            ,[ra_leadstage]
            ,[ra_leadstagename]
            ,[ra_ledby]
            ,[ra_ledbyname]
            ,[ra_legacyleadid]
            ,[ra_lmpcontactapr]
            ,[ra_lmpdateassigned]
            ,[ra_lmpdateclosed]
            ,[ra_lmpdatecreated]
            ,[ra_lmpdatemodified]
            ,[ra_lmplink]
            ,[ra_lmpopportunityproduct]
            ,[ra_lmpopportunitystatus]
            ,[ra_lmpopportunityvalue]
            ,[ra_lmpopportunityvalue_base]
            ,[ra_lmpowneremail]
            ,[ra_lmpstatus]
            ,[ra_opportunitygroup]
            ,[ra_opportunitygroupname]
            ,[ra_opportunityname]
            ,[ra_opportunitytype]
            ,[ra_opportunitytypename]
            ,[ra_opportunityzone]
            ,[ra_opportunityzonename]
            ,[ra_parentlead]
            ,[ra_parentleadname]
            ,[ra_primarycontactidentified]
            ,[ra_primarycontactidentifiedname]
            ,[ra_reroutetodistributor]
            ,[ra_reroutetodistributorname]
            ,[ra_salesaccepted]
            ,[ra_salesacceptedname]
            ,[ra_salesdisqualifyreason]
            ,[ra_salesdisqualifyreasonname]
            ,[ra_salesplanid]
            ,[ra_salesplanidname]
            ,[ra_salesqualified]
            ,[ra_salesqualifiedname]
            ,[ra_salesrejectionreason]
            ,[ra_salesrejectionreasonname]
            ,[ra_secondarysourcecampaign]
            ,[ra_secondarysourcecampaignname]
            ,[ra_specificationposition]
            ,[ra_specificationpositionname]
            ,[ra_stateprovinceid]
            ,[ra_stateprovinceidname]
            ,[ra_teleaccepted]
            ,[ra_teleacceptedname]
            ,[ra_teledisqualifyreason]
            ,[ra_teledisqualifyreasonname]
            ,[ra_telequalified]
            ,[ra_telequalifiedname]
            ,[ra_telerejectionreason]
            ,[ra_telerejectionreasonname]
            ,[ra_telerep]
            ,[ra_telerepname]
            ,[ra_wasteleperformed]
            ,[ra_wasteleperformedname]
            ,[ra_wouldyoulikefurthercontact]
            ,[ra_wouldyoulikefurthercontactname]
            ,[ra_z_internal_preventloopingofaccount]
            ,[ra_z_internal_preventloopingofaccountname]
            ,[ra_zcurrenter]
            ,[ra_zpreviouser]
            ,[ra_zsalesacceptancestageentered]
            ,[relatedobjectid]
            ,[relatedobjectidname]
            ,[revenue]
            ,[revenue_base]
            ,[salesstage]
            ,[salesstagecode]
            ,[salesstagecodename]
            ,[salesstagename]
            ,[salutation]
            ,[schedulefollowup_prospect]
            ,[schedulefollowup_qualify]
            ,[sic]
            ,[slaid]
            ,[slainvokedid]
            ,[slainvokedidname]
            ,[slaname]
            ,[stageid]
            ,[statecode]
            ,[statecodename]
            ,[statuscode]
            ,[statuscodename]
            ,[subject]
            ,[teamsfollowed]
            ,[telephone1]
            ,[telephone2]
            ,[telephone3]
            ,[timezoneruleversionnumber]
            ,[transactioncurrencyid]
            ,[transactioncurrencyidname]
            ,[utcconversiontimezonecode]
            ,[websiteurl]
            ,[owningbusinessunitname]
            ,[ra_integrationsource]
            ,[ra_integrationsourcename]
            ,[ra_externalrecordid]
            ,[ra_externalreroute]
            ,[ra_externalreroutename]
        FROM [Staging].[crm].[Lead]
        """
    return s




def get_elq_bridge_only_query():
    s = f"""    
        SELECT DISTINCT elq.[EloquaContactId], elq.[EmailAddress]
        FROM [Staging].[elq].[Contact] AS elq
        WHERE elq.[EloquaContactId]<>''
        """
    return s
